[package]
name = "not-a-rust-grep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "not-a-rust-grep"
path = "main.rs"
