[package]
include = ["Cargo.toml", "src/**/*.rs"]
name    = "not-a-rust-grep-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "not-a-rust-grep-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.10", features = ["derive"] }
