[package]
name    = "not-a-rust-grep-core"
edition = { workspace = true }
version = "0.1.0"

[[bin]]
name = "nrg"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap   = { version = "4.5.10", features = ["derive", "string"] }
